---
- name: 'Handler_Update_Timezone'
  ansible.builtin.shell: 'timedatectl set-timezone $(cat /etc/timezone)'
  become: true
  when:
  - ct_family == 'debian'
  tags:
  - ct-opsys-unix
  - skip_ansible_lint
...
